#! /bin/bash
#! /bin/bash
# Time-stamp: <2013-02-13 17:27 christophe@pallier.org>
# Time-stamp: <2012-06-11 14:10:20 am985309>

# read a list of subdirectories on the standard input and move the anat and fMRI files there

OWD=$PWD

# default directories...
ANAT_DIR=t1mri/acquisition1
FMRI_DIR=fMRI/acquisition1

# can be changed with options on the command line
while getopts ":a" opt; do
  case $opt in
    a)
	  ANAT_DIR=$OPTARG
	  ;;
    f)
	  FMRI_DIR=$OPTARG
	  ;;
    1)
	  ANAT_DIR=t1mri/acquisition1
	  FMRI_DIR=fMRI/acquisition1
	  ;;
    2)
	  ANAT_DIR=t1mri/acquisition2
	  FMRI_DIR=fMRI/acquisition2
	  ;;
    3)
	  ANAT_DIR=t1mri/acquisition3
	  FMRI_DIR=fMRI/acquisition3
	  ;;
    4)
	  ANAT_DIR=t1mri/acquisition4
	  FMRI_DIR=fMRI/acquisition4
	  ;;
    5)
	  ANAT_DIR=t1mri/acquisition5
	  FMRI_DIR=fMRI/acquisition5
	  ;;
    6)
	  ANAT_DIR=t1mri/acquisition6
	  FMRI_DIR=fMRI/acquisition6
	  ;;
  esac
done

while read SUJDIR ACQ; 
do
    if [ "x$SUJDIR" == "x" ] ; then continue ; fi
    if ( echo "$SUJDIR ++" | grep -vq "^#" ) ; then # skip lines starting with "#"
	cd $OWD/$SUJDIR
	mkdir -p $ANAT_DIR
	mkdir -p $FMRI_DIR
	find -maxdepth 1 -name 'anat*.nii' -exec mv '{}' $ANAT_DIR ';'
	find -maxdepth 1 -name '*.nii' -exec mv '{}' $FMRI_DIR ';'
	#find . -name '*.nii' -exec chmod -R a-w '{}' ';'
    fi
done

cd $OWD

