#! /bin/sh
# Time-stamp: <2011-05-03 11:46:58 cp983411>

# Beware: this will delete raw function files if their name start with [swr]
find -name '[wmrc]*anat*.nii' -delete
find -name 'rp*.txt' -delete
find -name '*.mat' -delete
find -name 'mean*.nii' -delete
find -name '[swr]*.nii' -delete
find -name 'a[^nat]*.nii' -delete
