#! /bin/bash
# Time-stamp: <2013-02-13 17:42 christophe@pallier.org>

if [ "$1" == "-h" ]
then
    echo Usage: 
    echo $0 " < list_subjects.txt"
    echo
    echo 
    echo Reads standard input line by line. 
    echo Each line must have the following format:
    echo   dirname date nip num1 name1 [num2 name2 [num3 name3 ...]
    echo where numXX specify the series\' number, using 2 digits
    echo ignore lines starting with \'#\'
    exit 1
fi

while read SUBJECT LINE
do
    if [ "x$SUBJECT" == "x" ] ; then continue ; fi
    if ( echo "$SUBJECT ++" | grep -vq "^#" ) ; then
	echo 
	echo "Creating directory $SUBJECT"
	mkdir -p $SUBJECT
	cd $SUBJECT 
	echo  "import_series_from_trio $LINE"
	import_scans_from_trio $LINE
	cd ..
    fi
done






